# Generated by Django 4.2 on 2023-07-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.PositiveIntegerField()),
                ('profesion', models.CharField(choices=[('Ninguna', 'Ninguna'), ('Estudiante', 'Estudiante'), ('Profesional', 'Profesional'), ('Educador', 'Educador')], default='Ninguna', max_length=20)),
                ('rut', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('confirmacion_email', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=128)),
                ('confirmacion_contraseña', models.CharField(max_length=128)),
                ('pais', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
